apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "store.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ include "store.database.rootPassword" . | quote }}
  MYSQL_DATABASE: {{ .Values.secrets.database.name | quote }}
  MYSQL_USER: {{ .Values.secrets.database.username | quote }}
  MYSQL_PASSWORD: {{ include "store.database.password" . | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-admin-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "store.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
type: Opaque
stringData:
  WORDPRESS_ADMIN_USER: {{ .Values.secrets.admin.username | quote }}
  WORDPRESS_ADMIN_PASSWORD: {{ include "store.admin.password" . | quote }}
  WORDPRESS_ADMIN_EMAIL: {{ .Values.secrets.admin.email | quote }}
